---
- include_vars: ../../../group_vars/cm_repo.yml
- include_vars: ../../../group_vars/user_vars.yml

- include: default_repo.yml
  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos") and (not local_repo)

- include: local_repo.yml
  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos") and (local_repo)
